notifications:
  email:
    on_success: change
    on_failure: change


language: go

go:
- 1.7

before_install:
- go get golang.org/x/tools/cmd/goimports
- go get github.com/mattn/goveralls

script:
- go vet
- go test -race
- ./.travis.goimports.sh

after_success:
- $HOME/gopath/bin/goveralls -service=travis-ci
