notifications:
  email:
    on_success: change
    on_failure: change


language: go

go:
- 1.7

before_install:
- make dep

script:
- make test

after_success:
- make coveralls

before_deploy:
- make dist

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
