notifications:
  email:
    on_success: change
    on_failure: change


language: go

go:
- 1.7

before_install:
- go get golang.org/x/tools/cmd/goimports
- go get github.com/mattn/goveralls

script:
- go vet
- go test -race
- ./.travis.goimports.sh

after_success:
- $HOME/gopath/bin/goveralls -service=travis-ci

before_deploy:
  - go get github.com/mitchellh/gox
  - export VERSION=`git describe --tags`
  - gox -os="linux freebsd" -arch="amd64 386" -output "dist/{{.OS}}_{{.Arch}}_awslogs" -ldflags "-X main.version=$VERSION"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
